services:
  one_diffusion:
    image: fhrozen/one_diffusion:latest
    build:
      context: .
      dockerfile: ./dev.dockerfile
      args:
        - TAG=fhrozen/python
    volumes:
      - ./models:/root/.cache/huggingface
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
