services:
  marker:
    image: fhrozen/marker-pdf:latest
    build:
      context: .
      dockerfile: ./dev.dockerfile
      args:
        - TAG=fhrozen/python
    volumes:
      - ./models:/root/.cache/huggingface
    ports:
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
