services:
  yue:
    image: fhrozen/yue:latest
    build:
      context: .
      dockerfile: ./dev.dockerfile
      args:
        - TAG=fhrozen/python
    volumes:
      - ./models:/root/.cache/huggingface
      - ./app:/opt/app
    ports:
      - "7865:7860"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
