services:
  hunyuan:
    image: fhrozen/hunyuan3d:latest
    build:
      context: .
      dockerfile: ./dev.dockerfile
      args:
        - TAG=fhrozen/python
        - TORCH_CUDA_ARCH_LIST='8.0;8.6+PTX'
        - APP_PROFILE=low  # change this for high
    volumes:
      - ./models:/root/.cache/huggingface
      # - ./Hunyuan3D-2:/opt/app  # Use this for high resources
      - ./Hunyuan3D-2GP:/opt/app  # Use this for low resources
      - ./models:/root/.u2net
    ports:
      - "8081:8080"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
