services:
  kokoro_tts:
    image: fhrozen/kokorotts:latest
    build:
      context: .
      dockerfile: ./dev.dockerfile
      args:
        - TAG=fhrozen/python
    volumes:
      - ./app:/opt/app
      - ./models:/opt/.huggingface
    ports:
      - "7861:7860"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
